head(iris,150)
Xdata=iris$Sepal.Length
MinQ=quantile(Xdata,0)
FQ=quantile(Xdata,0.25)
SQ=quantile(Xdata,0.5)
TQ=quantile(Xdata,0.75)
MaxQ=quantile(Xdata,1)
cat("Minimum=",MinQ)
cat("Lower Quartile=",FQ)
cat("Median=",SQ)
cat("Upper Quartile=",TQ)
cat("Maximum=",MaxQ)
AQ=quantile(Xdata,prob=c(0,0.25,0.5,0.75,1))
cat("All the Quartiles=",AQ)
summary(Xdata)
boxplot(Xdata,main="Interquartile Range for Sepal Length",ylab="centimeters")
as.numeric(quantile(Xdata,0.75)-quantile(Xdata,0.25))
IQR(xdata)